name: Beatrix CI

on: [ push, pull_request ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    services:
      postgresdb:
        image: postgres:11
        ports: [ '5432:5432' ]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.14.0'
        otp-version: '24.1'
    - name: Deps cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Deps install
      run: mix deps.get
    - name: Lint
      run: mix format --check-formatted
    - name: Tests
      run: mix test
